import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {parsePost,renderMarkdown,loadPosts} from '../scripts/content.mjs';
const front=(extra='',body='内容')=>`---\ntitle: 测试\ndate: '2026-10-02'\nslug: test\n${extra}\n---\n${body}`;
test('invalid dates and traversal slugs fail before publish',()=>{assert.throws(()=>parsePost(front().replace('2026-10-02','2026-02-31'),'a.md'));assert.throws(()=>parsePost(front().replace('slug: test','slug: ../secret'),'a.md'));});
test('drafts do not appear in the public content list',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'shixue-'));try{fs.writeFileSync(dir+'/public.md',front());fs.writeFileSync(dir+'/private.md',front('draft: true'));assert.equal(loadPosts(dir).length,1);}finally{fs.rmSync(dir,{recursive:true});}});
test('Markdown renders headings, tables, images and highlighted code safely',()=>{const r=renderMarkdown('## 标题\n\n**粗体**\n\n| a | b |\n| --- | --- |\n| 1 | 2 |\n\n![图片](images/test.png)\n\n```js\nconst a = 1;\n```\n\n<script>alert(1)</script>\n\n[bad](javascript:alert(1))','/blog/');assert.equal(r.toc[0].id,'section-1');assert.match(r.html,/<table>/);assert.match(r.html,/src="\/blog\/images\/test.png"/);assert.match(r.html,/hljs-keyword/);assert.doesNotMatch(r.html,/<script|href="javascript:/);});
test('math renders inline and display formulas without enabling unsafe HTML commands',()=>{const r=renderMarkdown('公式 $E=mc^2$\n\n$$\n\\frac{1}{2}\n$$\n\n`$code$`\n\n```text\n$literal$\n```\n\n$\\href{javascript:alert(1)}{x}$\n\n<img src=x onerror=alert(1)>');assert.match(r.html,/katex/);assert.match(r.html,/katex-display/);assert.match(r.html,/<code>\$code\$<\/code>/);assert.match(r.html,/\$literal\$/);assert.doesNotMatch(r.html,/href="javascript:|onerror=/);assert.doesNotMatch(r.html,/SHIXUEMATH/);});
test('series metadata accepts positive sequence numbers only',()=>{const p=parsePost(front('series: 编程\nseriesOrder: 2'),'s.md');assert.equal(p.series,'编程');assert.equal(p.seriesOrder,2);for(const value of ['-1','0','1.5','"2"'])assert.throws(()=>parsePost(front('seriesOrder: '+value),'s.md'));});

test('math in image descriptions remains plain alternative text',()=>{const r=renderMarkdown('![$E=mc^2$](images/example.png)');assert.match(r.html,/alt="\$E=mc\^2\$"/);assert.doesNotMatch(r.html,/SHIXUEMATH|class="katex"/);});
