import fs from 'node:fs';
import {build} from 'esbuild';
import {orderedSeries} from '../lib/draft.mjs';
import path from 'node:path';
import {escape as e,loadPosts,renderMarkdown} from './content.mjs';
const root=process.cwd(),cfg=JSON.parse(fs.readFileSync('site.config.json','utf8')),posts=loadPosts('content/posts');
const prefix=String(process.env.BASE_PATH||'').replace(/^\/+|\/+$/g,''),base=prefix?`/${prefix}/`:'/',origin=process.env.SITE_ORIGIN||'';
const slugs=new Set();for(const p of posts){if(slugs.has(p.slug))throw new Error('文章 slug 重复: '+p.slug);slugs.add(p.slug);}
const out=path.join(root,'dist');fs.rmSync(out,{recursive:true,force:true});fs.mkdirSync(out,{recursive:true});fs.cpSync('public',out,{recursive:true});fs.copyFileSync('node_modules/highlight.js/styles/github-dark.min.css',out+'/highlight.css');
fs.mkdirSync(out+'/katex',{recursive:true});fs.cpSync('node_modules/katex/dist/fonts',out+'/katex/fonts',{recursive:true});fs.copyFileSync('node_modules/katex/dist/katex.min.css',out+'/katex/katex.min.css');
await build({entryPoints:['src/writer.mjs'],bundle:true,minify:true,format:'iife',outfile:out+'/writer.js',target:['es2020']});
const seriesNames=[...new Set(posts.map(p=>p.series).filter(Boolean))];
const url=p=>base+p,postUrl=p=>url(`posts/${p.slug}/`),github=`https://github.com/${cfg.githubRepository}`,categories=[...new Set(posts.map(p=>p.category))],tags=[...new Set(posts.flatMap(p=>p.tags))],format=d=>d.replace(/-/g,'.');
function cards(list){return list.map(p=>`<article class="post-card" data-category="${e(p.category)}" data-tags="${e(p.tags.join('|'))}" data-text="${e((p.title+' '+p.body+' '+p.tags.join(' ')).toLowerCase())}"><div class="meta"><time datetime="${p.date}">${format(p.date)}</time><span>${e(p.category)}</span></div><h2><a href="${postUrl(p)}">${e(p.title)}</a></h2><p>${e(p.summary)}</p></article>`).join('');}
function seriesList(name){return `<ol class="series-list">${orderedSeries(posts,name).map(p=>`<li><a href="${postUrl(p)}">${p.seriesOrder?e(p.seriesOrder)+'. ':''}${e(p.title)}</a></li>`).join('')}</ol>`;}
function music(){return `<div class="music-dock"><button id="music-open" aria-expanded="false" aria-controls="music-panel"><span class="disc">♫</span><span id="dock-title">音乐</span><span>⌃</span></button><section id="music-panel" hidden aria-label="音乐播放器"><div class="music-heading"><strong>学习歌单</strong><button id="music-close" aria-label="收起播放器">×</button></div><div class="now-playing"><span class="record">♫</span><div><b id="track-title"></b><small id="track-artist"></small></div></div><audio id="audio" preload="none"></audio><input id="seek" type="range" min="0" max="100" value="0" aria-label="播放进度"><div class="time"><span id="current">0:00</span><span id="duration">0:00</span></div><div class="player-controls"><button id="previous" aria-label="上一首">◁</button><button id="play" aria-label="播放">▶</button><button id="next" aria-label="下一首">▷</button><button id="repeat" aria-label="切换单曲循环" aria-pressed="false">↻</button></div><label class="volume">音量<input id="volume" type="range" min="0" max="1" step=".01" value=".5" aria-label="音量"></label><div id="playlist"></div><label class="local-song">＋ 选择本地歌曲<input id="local-music" type="file" accept="audio/*" multiple></label><p id="music-error" role="status"></p><p class="credits" id="music-credits">初始音乐：Carefree · Kevin MacLeod<br><a href="https://incompetech.com/" target="_blank" rel="noopener">incompetech.com</a> · <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank" rel="noopener">CC BY 4.0</a> · 未修改<br>本地歌曲只在本次访问中播放。</p></section></div>`;}
function layout(title,body,route=''){const full=title?title+' · '+cfg.title:cfg.title+' · '+cfg.subtitle;return `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${e(full)}</title><meta name="description" content="${e(cfg.description)}"><meta name="site-base" content="${base}"><meta name="github-repository" content="${e(cfg.githubRepository)}">${origin?`<link rel="canonical" href="${origin}${url(route)}">`:''}<link rel="icon" href="${url('favicon.svg')}"><link rel="stylesheet" href="${url('style.css')}"><link rel="stylesheet" href="${url('highlight.css')}"><link rel="stylesheet" href="${url('katex/katex.min.css')}">${route==='write/'?`<script defer src="${url('writer.js')}"></script>`:''}<script src="${url('theme.js')}"></script><script defer src="${url('app.js')}"></script></head><body><a class="skip" href="#main">跳到正文</a><header><a class="brand" href="${base}">${e(cfg.title)}<span>学习手记</span></a><nav aria-label="主导航"><a ${route===''?'aria-current="page"':''} href="${base}">笔记</a><a ${route==='archive/'?'aria-current="page"':''} href="${url('archive/')}">归档</a><a ${route==='about/'?'aria-current="page"':''} href="${url('about/')}">关于</a></nav><a class="write-link" href="${url('write/')}">写一篇</a></header><main id="main"><div class="main-column">${body}</div></main><footer><span>© ${e(cfg.author)} · ${e(cfg.title)}</span><div class="footer-links"><button id="theme-toggle" aria-label="切换深浅主题">外观</button>${music()}<a href="${github}" target="_blank" rel="noopener">GitHub</a></div></footer><button id="back-top" aria-label="返回顶部" hidden>↑</button><div id="toast" role="status" hidden></div></body></html>`;}
function write(file,html){fs.mkdirSync(path.dirname(out+'/'+file),{recursive:true});fs.writeFileSync(out+'/'+file,html);}
const intro=`<section class="intro"><p class="author-note">${e(cfg.author)} 的个人博客</p><h1>学习手记</h1><p>记下学到的东西，还有一些自己的想法。</p></section>`;
write('index.html',layout('',intro+`<div class="list-heading"><span id="result-count">${posts.length} 篇笔记</span><label class="search"><input id="search" type="search" placeholder="搜索笔记" aria-label="搜索笔记"></label></div>${categories.length>1?`<div class="filters"><button class="selected" data-filter="">全部</button>${categories.map(c=>`<button data-filter="${e(c)}">${e(c)}</button>`).join('')}</div>`:''}<div id="post-list">${cards(posts)}</div><div id="empty" ${posts.length?'hidden':''}><h3>还没有笔记</h3><p>写下第一篇，从今天学到的一件事开始。</p><a class="button primary" href="${url('write/')}">写一篇</a></div>`));
for(let i=0;i<posts.length;i++){const p=posts[i],r=renderMarkdown(p.body,base),wordcount=p.body.replace(/\s/g,'').length;
write(`posts/${p.slug}/index.html`,layout(p.title,`<a class="back" href="${base}">返回笔记</a><article class="reading"><div class="meta"><span class="badge">${e(p.category)}</span><time>${format(p.date)}</time><span>${wordcount} 字</span></div><h1>${e(p.title)}</h1><p class="byline">${e(cfg.author)}</p><details class="article-directory"><summary>文章目录</summary>${r.toc.map(h=>`<a class="toc-item depth-${h.depth}" href="#${h.id}">${e(h.title)}</a>`).join('')}</details><div class="prose">${r.html}</div>${p.series?`<section class="series-box"><h2>${e(p.series)}</h2><p class="muted">${p.seriesOrder?`当前：第 ${p.seriesOrder} 篇 · `:''}同系列学习笔记</p>${seriesList(p.series)}</section>`:''}<div class="tag-row">${p.tags.map(t=>`<a href="${url('tags/')}#${encodeURIComponent(t)}"># ${e(t)}</a>`).join('')}</div><div class="article-bottom"><button class="text-button" id="share-mobile">分享这篇</button><a href="${github}/edit/main/content/posts/${encodeURIComponent(p.file)}" target="_blank" rel="noopener">编辑文章</a></div><div class="adjacent">${posts[i+1]?`<a href="${postUrl(posts[i+1])}"><small>上一篇</small>${e(posts[i+1].title)}</a>`:'<span></span>'}${posts[i-1]?`<a href="${postUrl(posts[i-1])}"><small>下一篇</small>${e(posts[i-1].title)}</a>`:''}</div></article>`,`posts/${p.slug}/`));fs.mkdirSync(out+'/markdown',{recursive:true});fs.copyFileSync('content/posts/'+p.file,out+'/markdown/'+p.file);}
const groups=Object.groupBy(posts,p=>p.date.slice(0,7));write('archive/index.html',layout('文章归档',`<section class="page-intro"><h1>所有笔记</h1><p>${posts.length} 篇笔记 · <a href="${url('tags/')}">按标签找</a> · <a href="${url('series/')}">查看系列</a></p></section>${Object.entries(groups).map(([month,list])=>`<section class="archive"><h2>${month.replace('-',' 年 ')} 月 <small>${list.length} 篇</small></h2>${list.map(p=>`<a href="${postUrl(p)}"><time>${p.date.slice(5).replace('-',' / ')}</time><b>${e(p.title)}</b><span>${e(p.category)}</span></a>`).join('')}</section>`).join('')||'<p class="muted">第一篇笔记保存后，会出现在这里。</p>'}`,'archive/'));
write('tags/index.html',layout('标签',`<section class="page-intro"><h1>标签</h1><p>找到同一个话题下的笔记。</p></section><div class="tag-cloud">${tags.map(t=>`<a href="#${encodeURIComponent(t)}"># ${e(t)} <small>${posts.filter(p=>p.tags.includes(t)).length}</small></a>`).join('')}</div>${tags.map(t=>`<section class="tag-group" id="${e(t)}"><h2># ${e(t)}</h2>${cards(posts.filter(p=>p.tags.includes(t)))}</section>`).join('')||'<p class="muted">给笔记添加标签，在这里找到它们。</p>'}`,'tags/'));
write('about/index.html',layout('关于',`<section class="page-intro"><h1>关于这里</h1></section><div class="prose"><p>${e(cfg.about)}</p><h2>我想留下什么</h2><p>值得反复读的笔记、实践中的发现，以及那些还没有想明白的问题。写下来，是为了更好地理解，也是为了以后还能找回来。</p><h2>慢慢来，也是一种进步</h2><p>这里的内容会随学习不断更新。欢迎阅读，也欢迎带着自己的问题继续探索。</p></div>`,'about/'));
write('series/index.html',layout('系列笔记',`<section class="page-intro"><h1>系列笔记</h1><p>把相关笔记放在一起，沿着自己的节奏深入学习。</p></section>${seriesNames.map(name=>`<section class="series-box"><h2>${e(name)}</h2><p class="muted">${orderedSeries(posts,name).length} 篇笔记</p>${seriesList(name)}</section>`).join('')||`<div class="series-box"><h2>你的第一个系列，从下一篇开始。</h2><p>写笔记时填写相同的「系列名称」和每篇的序号，发布后就会自动形成目录。</p><a class="button primary" href="${url('write/')}">写一篇系列笔记</a></div>`}`,'series/'));
write('write/index.html',layout('写笔记',`<section class="page-intro writer-intro"><h1>写一篇笔记</h1><p>先写下来，之后再慢慢补充。</p></section><section class="writer"><fieldset data-writer-control disabled><label class="title-label"><span class="sr-only">文章标题</span><input id="draft-title" placeholder="标题" maxlength="200" autocomplete="off"></label><div class="editor-tools"><button type="button" id="insert-image">插入图片</button><button type="button" id="toggle-preview" aria-pressed="false">预览</button><input id="image-file" type="file" accept="image/png,image/jpeg,image/webp,image/gif" multiple hidden></div><div class="editor-workspace" data-view="edit"><label class="edit-pane"><span class="sr-only">正文</span><textarea id="draft-body" rows="16" placeholder="今天学到了什么？从这里开始写。" aria-describedby="markdown-hint"></textarea></label><section class="preview-pane" aria-label="文章预览"><h2 id="preview-title"></h2><div id="draft-preview" class="prose"></div></section></div><div class="editor-bottom"><p id="save-status" role="status" aria-live="polite">正在恢复草稿…</p><span id="word-count">0 字</span><button type="button" id="download-draft" class="button primary">下载笔记</button></div><details class="writer-settings"><summary>更多设置与草稿</summary><div class="settings-content"><div class="draft-bar"><label>我的草稿<select id="draft-list" aria-label="选择草稿"></select></label><button type="button" id="new-draft" class="text-button">新建</button><button type="button" id="delete-draft" class="text-button">删除当前草稿</button></div><div class="writer-fields"><label>分类<input id="draft-category"></label><label>日期<input id="draft-date" type="date"></label></div><label>标签<input id="draft-tags" placeholder="用逗号分隔"></label><label>网址名<input id="draft-slug" placeholder="自动生成，可修改为小写英文"></label><div class="writer-fields"><label>系列名称<input id="draft-series" placeholder="可不填"></label><label>系列序号<input id="draft-seriesOrder" type="number" min="1" step="1" placeholder="可不填"></label></div><div class="image-details"><h3>图片附件</h3><div id="image-assets"></div></div><p class="muted" id="markdown-hint">支持 Markdown：## 标题、**粗体**、代码块和数学公式。直接写普通文字也可以。</p><p class="muted">草稿保存在当前浏览器。清除浏览器数据会删除草稿，重要内容请下载备份。</p></div></details></fieldset><details class="publish-guide"><summary>怎么让别人看到？</summary><p>点击「下载笔记」，再把文件上传到 <a href="${github}/upload/main/content/posts" target="_blank" rel="noopener">GitHub 文章目录</a>并提交，网站会自动更新。</p><p>有图片时会自动下载 ZIP。解压后，文章上传到 content/posts，图片上传到 <a href="${github}/upload/main/public/images" target="_blank" rel="noopener">public/images</a>。</p><p class="muted">下载和保存草稿不会公开发布。只有拥有仓库写入权限的人能修改博客。</p></details></section>`,'write/'));
write('404.html',layout('没有找到页面',`<section class="page-intro"><h1>这一页，还没有写下。</h1><p>文章可能已移动，你可以回到首页寻找。</p><a class="button primary" href="${base}">返回笔记</a></section>`));
fs.writeFileSync(out+'/music.json',JSON.stringify(cfg.music));fs.writeFileSync(out+'/search.json',JSON.stringify(posts.map(p=>({title:p.title,category:p.category,tags:p.tags,url:postUrl(p)}))));fs.writeFileSync(out+'/.nojekyll','');
if(origin){const urls=['','archive/','tags/','series/','about/',...posts.map(p=>`posts/${p.slug}/`)];fs.writeFileSync(out+'/sitemap.xml',`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${urls.map(p=>`<url><loc>${e(origin+url(p))}</loc></url>`).join('')}</urlset>`);fs.writeFileSync(out+'/feed.xml',`<?xml version="1.0" encoding="UTF-8"?><rss version="2.0"><channel><title>${e(cfg.title)}</title><link>${e(origin+base)}</link><description>${e(cfg.description)}</description>${posts.map(p=>`<item><title>${e(p.title)}</title><link>${e(origin+postUrl(p))}</link><guid>${e(origin+postUrl(p))}</guid><pubDate>${new Date(p.date+'T12:00:00Z').toUTCString()}</pubDate><description>${e(p.summary)}</description></item>`).join('')}</channel></rss>`);}
console.log(`Built ${posts.length} posts at ${base}`);
