import fs from 'node:fs';
import path from 'node:path';
import {escape as e,loadPosts,renderMarkdown} from './content.mjs';
const root=process.cwd(),cfg=JSON.parse(fs.readFileSync('site.config.json','utf8')),posts=loadPosts('content/posts');
const prefix=String(process.env.BASE_PATH||'').replace(/^\/+|\/+$/g,''),base=prefix?`/${prefix}/`:'/',origin=process.env.SITE_ORIGIN||'';
const slugs=new Set();for(const p of posts){if(slugs.has(p.slug))throw new Error('文章 slug 重复: '+p.slug);slugs.add(p.slug);}
const out=path.join(root,'dist');fs.rmSync(out,{recursive:true,force:true});fs.mkdirSync(out,{recursive:true});fs.cpSync('public',out,{recursive:true});fs.copyFileSync('node_modules/highlight.js/styles/github-dark.min.css',out+'/highlight.css');
const url=p=>base+p,postUrl=p=>url(`posts/${p.slug}/`),github=`https://github.com/${cfg.githubRepository}`,categories=[...new Set(posts.map(p=>p.category))],tags=[...new Set(posts.flatMap(p=>p.tags))],format=d=>d.replace(/-/g,'.');
function cards(list){return list.map((p,i)=>`<article class="post-card" data-category="${e(p.category)}" data-tags="${e(p.tags.join('|'))}" data-text="${e((p.title+' '+p.body+' '+p.tags.join(' ')).toLowerCase())}"><span class="card-number">${String(list.length-i).padStart(2,'0')}</span><div><div class="meta"><span class="badge">${e(p.category)}</span><time datetime="${p.date}">${format(p.date)}</time><span>${Math.max(1,Math.ceil(p.body.length/450))} 分钟阅读</span></div><h2><a href="${postUrl(p)}">${e(p.title)}</a></h2><p>${e(p.summary)}</p><div class="tag-row">${p.tags.map(t=>`<a href="${url('tags/')}#${encodeURIComponent(t)}"># ${e(t)}</a>`).join('')}</div><a class="read-link" href="${postUrl(p)}">阅读笔记</a></div></article>`).join('');}
function sidebar(){return `<aside class="sidebar"><section class="profile"><div class="avatar">学</div><span>学习是一场持续的探索</span><h2>保持好奇，<br>持续记录。</h2><p>${e(cfg.author)} 的学习手记。<br>不必写得完美，开始记录就好。</p><div class="profile-count"><b>${posts.length}<small>篇笔记</small></b><b>${categories.length}<small>个分类</small></b></div></section><section class="side-section"><h3>笔记分类</h3>${categories.map(c=>`<a href="${url('')}?category=${encodeURIComponent(c)}"><span>${e(c)}</span><small>${posts.filter(p=>p.category===c).length}</small></a>`).join('')||'<p class="muted">你的知识目录会慢慢长出来。</p>'}</section><section class="side-section"><h3>最近写下</h3>${posts.slice(0,3).map(p=>`<a class="recent" href="${postUrl(p)}"><span>${e(p.title)}</span><small>${format(p.date)}</small></a>`).join('')}</section><section class="side-section"><h3>写作空间</h3><a href="${url('write/')}">写一篇新笔记 <span>＋</span></a><a href="${github}" target="_blank" rel="noopener">GitHub 仓库 </a></section></aside>`;}
function music(){return `<div class="music-dock"><button id="music-open" aria-expanded="false" aria-controls="music-panel"><span class="disc">♫</span><span id="dock-title">阅读时，听一点音乐</span><span>⌃</span></button><section id="music-panel" hidden aria-label="音乐播放器"><div class="music-heading"><strong>学习歌单</strong><button id="music-close" aria-label="收起播放器">×</button></div><div class="now-playing"><span class="record">♫</span><div><b id="track-title"></b><small id="track-artist"></small></div></div><audio id="audio" preload="none"></audio><input id="seek" type="range" min="0" max="100" value="0" aria-label="播放进度"><div class="time"><span id="current">0:00</span><span id="duration">0:00</span></div><div class="player-controls"><button id="previous" aria-label="上一首">◁</button><button id="play" aria-label="播放">▶</button><button id="next" aria-label="下一首">▷</button><button id="repeat" aria-label="切换单曲循环" aria-pressed="false">↻</button></div><label class="volume">音量<input id="volume" type="range" min="0" max="1" step=".01" value=".5" aria-label="音量"></label><div id="playlist"></div><label class="local-song">＋ 选择本地歌曲<input id="local-music" type="file" accept="audio/*" multiple></label><p id="music-error" role="status"></p><p class="credits" id="music-credits">初始音乐：Carefree · Kevin MacLeod<br><a href="https://incompetech.com/" target="_blank" rel="noopener">incompetech.com</a> · <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank" rel="noopener">CC BY 4.0</a> · 未修改<br>本地歌曲只在本次访问中播放。</p></section></div>`;}
function layout(title,body,route='',extra=''){const full=title?title+' · '+cfg.title:cfg.title+' · '+cfg.subtitle;return `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${e(full)}</title><meta name="description" content="${e(cfg.description)}"><meta name="site-base" content="${base}"><meta name="github-repository" content="${e(cfg.githubRepository)}">${origin?`<link rel="canonical" href="${origin}${url(route)}">`:''}<link rel="icon" href="${url('favicon.svg')}"><link rel="stylesheet" href="${url('style.css')}"><link rel="stylesheet" href="${url('highlight.css')}"><script src="${url('theme.js')}"></script><script defer src="${url('app.js')}"></script></head><body><a class="skip" href="#main">跳到正文</a><header><a class="brand" href="${base}"><span class="brand-icon">拾</span><b>${e(cfg.title)}<small>SHIXUE JOURNAL</small></b></a><nav><a ${route===''?'class="active"':''} href="${base}">笔记</a><a href="${url('archive/')}">归档</a><a href="${url('tags/')}">标签</a><a href="${url('about/')}">关于</a></nav><button id="theme-toggle" aria-label="切换深浅主题">◐</button><a class="button primary top-write" href="${url('write/')}">写笔记</a></header><main id="main"><div class="layout"><div class="main-column">${body}</div>${extra||sidebar()}</div><footer><b>拾学</b><span>把学习写下来，让成长有迹可循。</span><a href="${github}" target="_blank" rel="noopener">GitHub</a></footer></main>${music()}<button id="back-top" aria-label="返回顶部" hidden>↑</button><div id="toast" role="status" hidden></div></body></html>`;}
function write(file,html){fs.mkdirSync(path.dirname(out+'/'+file),{recursive:true});fs.writeFileSync(out+'/'+file,html);}
const intro=`<section class="intro"><span class="eyebrow">MY LEARNING JOURNAL</span><h1>学过的，想过的，<br>都留在这里<span>。</span></h1><p>记录学习的片段，也记录慢慢成长的自己。</p><div class="intro-line"><i></i><small>一点一滴，日有所进</small></div></section>`;
write('index.html',layout('',intro+`<div class="list-heading"><h2>最近的笔记 <small id="result-count">${posts.length} 篇</small></h2><label class="search">⌕<input id="search" type="search" placeholder="寻找一段笔记…" aria-label="搜索笔记"></label></div><div class="filters"><button class="selected" data-filter="">全部文章</button>${categories.map(c=>`<button data-filter="${e(c)}">${e(c)}</button>`).join('')}</div><div id="post-list">${cards(posts)}</div><div id="empty" ${posts.length?'hidden':''}><h3>笔记，正在路上。</h3><p>从一个知识点、一段思考、一场实践开始。</p><a class="button primary" href="${url('write/')}">写下第一篇笔记</a></div>`));
for(let i=0;i<posts.length;i++){const p=posts[i],r=renderMarkdown(p.body,base),wordcount=p.body.replace(/\s/g,'').length;const toc=`<aside class="sidebar toc-sidebar"><section class="side-section"><h3>文章目录</h3>${r.toc.map(h=>`<a class="toc-item depth-${h.depth}" href="#${h.id}">${e(h.title)}</a>`).join('')||'<p class="muted">这是一篇短笔记。</p>'}</section><section class="side-section"><h3>这篇笔记</h3><p class="muted">${wordcount} 字 · 约 ${Math.max(1,Math.ceil(wordcount/450))} 分钟</p><button class="text-button" id="share">复制文章链接</button><a href="${github}/edit/main/content/posts/${encodeURIComponent(p.file)}" target="_blank" rel="noopener">编辑这篇笔记</a></section></aside>`;
write(`posts/${p.slug}/index.html`,layout(p.title,`<a class="back" href="${base}">返回笔记</a><article class="reading"><div class="meta"><span class="badge">${e(p.category)}</span><time>${format(p.date)}</time><span>${wordcount} 字</span></div><h1>${e(p.title)}</h1><div class="byline"><span class="avatar mini">学</span><span>${e(cfg.author)}<small>每一次记录，都是一次积累。</small></span></div><div class="prose">${r.html}</div><div class="tag-row">${p.tags.map(t=>`<a href="${url('tags/')}#${encodeURIComponent(t)}"># ${e(t)}</a>`).join('')}</div><div class="article-bottom"><button class="button outline" id="copy-markdown" data-file="${url('markdown/'+p.file)}">下载 Markdown</button><button class="button outline" id="share-mobile">复制链接</button></div><div class="adjacent">${posts[i+1]?`<a href="${postUrl(posts[i+1])}"><small>上一篇</small>${e(posts[i+1].title)}</a>`:'<span></span>'}${posts[i-1]?`<a href="${postUrl(posts[i-1])}"><small>下一篇</small>${e(posts[i-1].title)}</a>`:''}</div></article>`,`posts/${p.slug}/`,toc));fs.mkdirSync(out+'/markdown',{recursive:true});fs.copyFileSync('content/posts/'+p.file,out+'/markdown/'+p.file);}
const groups=Object.groupBy(posts,p=>p.date.slice(0,7));write('archive/index.html',layout('文章归档',`<section class="page-intro"><span class="eyebrow">LOOKING BACK</span><h1>翻一翻，走过的路。</h1><p>${posts.length} 篇笔记，每一次记录都算数。</p></section>${Object.entries(groups).map(([month,list])=>`<section class="archive"><h2>${month.replace('-',' 年 ')} 月 <small>${list.length} 篇</small></h2>${list.map(p=>`<a href="${postUrl(p)}"><time>${p.date.slice(5).replace('-',' / ')}</time><b>${e(p.title)}</b><span>${e(p.category)}</span></a>`).join('')}</section>`).join('')||'<p class="muted">第一篇笔记保存后，会出现在这里。</p>'}`,'archive/'));
write('tags/index.html',layout('标签',`<section class="page-intro"><span class="eyebrow">CONNECT THE DOTS</span><h1>让知识彼此相连。</h1><p>沿着一个标签，找到相关的思考。</p></section><div class="tag-cloud">${tags.map(t=>`<a href="#${encodeURIComponent(t)}"># ${e(t)} <small>${posts.filter(p=>p.tags.includes(t)).length}</small></a>`).join('')}</div>${tags.map(t=>`<section class="tag-group" id="${e(t)}"><h2># ${e(t)}</h2>${cards(posts.filter(p=>p.tags.includes(t)))}</section>`).join('')||'<p class="muted">给笔记添加标签，在这里找到它们。</p>'}`,'tags/'));
write('about/index.html',layout('关于',`<section class="page-intro"><span class="eyebrow">HELLO, CURIOUS MIND</span><h1>关于这本学习手记。</h1></section><div class="prose"><p>${e(cfg.about)}</p><h2>我想留下什么</h2><p>值得反复读的笔记、实践中的发现，以及那些还没有想明白的问题。写下来，是为了更好地理解，也是为了以后还能找回来。</p><h2>慢慢来，也是一种进步</h2><p>这里的内容会随学习不断更新。欢迎阅读，也欢迎带着自己的问题继续探索。</p></div>`,'about/'));
write('write/index.html',layout('写笔记',`<section class="page-intro"><span class="eyebrow">A PAGE OF YOUR JOURNEY</span><h1>写下今天的收获。</h1><p>在这里起草，下载后提交到 GitHub，文章就会出现在博客。</p></section><section class="writer"><label>文章标题<input id="draft-title" placeholder="给这篇笔记起个标题" maxlength="200"></label><div class="writer-fields"><label>分类<input id="draft-category" value="学习随笔"></label><label>日期<input id="draft-date" type="date"></label></div><label>标签<input id="draft-tags" placeholder="用逗号分隔，如：编程, 实践"></label><label>文章网址名<input id="draft-slug" placeholder="my-first-note（小写英文、数字或短横线）"></label><label>正文<textarea id="draft-body" rows="15" placeholder="今天学到了什么？支持 Markdown 标题、列表、代码、图片…"></textarea></label><div class="writer-actions"><button id="download-draft" class="button primary">下载 Markdown</button><a class="button outline" href="${github}/upload/main/content/posts" target="_blank" rel="noopener">上传到 GitHub</a></div><p class="muted">此页面不会把文章直接发布。仅仓库所有者或有写入权限的人可以提交修改。请把下载的 .md 文件上传到 content/posts。</p></section>`,'write/'));
write('404.html',layout('没有找到页面',`<section class="page-intro"><span class="eyebrow">404</span><h1>这一页，还没有写下。</h1><p>文章可能已移动，你可以回到首页寻找。</p><a class="button primary" href="${base}">返回笔记</a></section>`));
fs.writeFileSync(out+'/music.json',JSON.stringify(cfg.music));fs.writeFileSync(out+'/search.json',JSON.stringify(posts.map(p=>({title:p.title,category:p.category,tags:p.tags,url:postUrl(p)}))));fs.writeFileSync(out+'/.nojekyll','');
if(origin){const urls=['','archive/','tags/','about/',...posts.map(p=>`posts/${p.slug}/`)];fs.writeFileSync(out+'/sitemap.xml',`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${urls.map(p=>`<url><loc>${e(origin+url(p))}</loc></url>`).join('')}</urlset>`);fs.writeFileSync(out+'/feed.xml',`<?xml version="1.0" encoding="UTF-8"?><rss version="2.0"><channel><title>${e(cfg.title)}</title><link>${e(origin+base)}</link><description>${e(cfg.description)}</description>${posts.map(p=>`<item><title>${e(p.title)}</title><link>${e(origin+postUrl(p))}</link><guid>${e(origin+postUrl(p))}</guid><pubDate>${new Date(p.date+'T12:00:00Z').toUTCString()}</pubDate><description>${e(p.summary)}</description></item>`).join('')}</channel></rss>`);}
console.log(`Built ${posts.length} posts at ${base}`);
