import fs from 'node:fs';
import {createHash} from 'node:crypto';
import {build} from 'esbuild';
import {orderedSeries} from '../lib/draft.mjs';
import path from 'node:path';
import {escape as e,loadPosts,renderMarkdown} from './content.mjs';
const root=process.cwd(),cfg=JSON.parse(fs.readFileSync('site.config.json','utf8')),posts=loadPosts('content/posts');
const prefix=String(process.env.BASE_PATH||'').replace(/^\/+|\/+$/g,''),base=prefix?`/${prefix}/`:'/',origin=process.env.SITE_ORIGIN||'';
const slugs=new Set();for(const p of posts){if(slugs.has(p.slug))throw new Error('文章 slug 重复: '+p.slug);slugs.add(p.slug);}
const out=path.join(root,'dist');fs.rmSync(out,{recursive:true,force:true});fs.mkdirSync(out,{recursive:true});fs.cpSync('public',out,{recursive:true});fs.copyFileSync('node_modules/highlight.js/styles/github-dark.min.css',out+'/highlight.css');
fs.mkdirSync(out+'/katex',{recursive:true});fs.cpSync('node_modules/katex/dist/fonts',out+'/katex/fonts',{recursive:true});fs.copyFileSync('node_modules/katex/dist/katex.min.css',out+'/katex/katex.min.css');
await build({entryPoints:['src/writer.mjs'],bundle:true,minify:true,format:'iife',outfile:out+'/writer.js',target:['es2020']});
await build({entryPoints:['src/drafts.mjs'],bundle:true,minify:true,format:'iife',outfile:out+'/drafts.js',target:['es2020']});
const seriesNames=[...new Set(posts.map(p=>p.series).filter(Boolean))];
const url=p=>base+p,postUrl=p=>url(`posts/${p.slug}/`),github=`https://github.com/${cfg.githubRepository}`,categories=[...new Set(posts.map(p=>p.category))],tags=[...new Set(posts.flatMap(p=>p.tags))],format=d=>d.replace(/-/g,'.');
const categoryRoute=name=>'categories/'+createHash('sha256').update(name).digest('hex').slice(0,16)+'/';
const navItems=[['','首页'],['notes/','笔记'],['topics/','专题'],['drafts/','草稿'],['music/','音乐'],['about/','关于']];
function subnav(active){return `<nav class="section-nav" aria-label="笔记浏览方式">${[['notes/','全部笔记'],['archive/','按时间'],['tags/','按标签'],['topics/','按专题']].map(([r,label])=>`<a href="${url(r)}" ${active===r?'aria-current="page"':''}>${label}</a>`).join('')}</nav>`;}
function cards(list){return list.map(p=>`<article class="post-card" data-category="${e(p.category)}" data-tags="${e(p.tags.join('|'))}" data-text="${e((p.title+' '+p.body+' '+p.tags.join(' ')).toLowerCase())}"><div class="meta"><time datetime="${p.date}">${format(p.date)}</time><span>${e(p.category)}</span></div><h2><a href="${postUrl(p)}">${e(p.title)}</a></h2><p>${e(p.summary)}</p></article>`).join('');}
function seriesList(name){return `<ol class="series-list">${orderedSeries(posts,name).map(p=>`<li><a href="${postUrl(p)}">${p.seriesOrder?e(p.seriesOrder)+'. ':''}${e(p.title)}</a></li>`).join('')}</ol>`;}
function music(){return `<section class="music-room" aria-label="音乐播放器"><div class="now-playing"><span class="record">♫</span><div><b id="track-title">正在加载歌单</b><small id="track-artist"></small></div></div><audio id="audio" preload="none"></audio><input id="seek" type="range" min="0" max="100" value="0" aria-label="播放进度"><div class="time"><span id="current">0:00</span><span id="duration">0:00</span></div><div class="player-controls"><button id="previous" aria-label="上一首">◁</button><button id="play" aria-label="播放">▶</button><button id="next" aria-label="下一首">▷</button><button id="repeat" aria-label="切换单曲循环" aria-pressed="false">↻</button></div><label class="volume">音量<input id="volume" type="range" min="0" max="1" step=".01" value=".5" aria-label="音量"></label><h2 class="playlist-title">歌单</h2><div id="playlist"></div><label class="local-song">选择本地歌曲<input id="local-music" type="file" accept="audio/*" multiple></label><p id="music-error" role="status"></p><p class="credits" id="music-credits"></p></section>`;}
function layout(title,body,route=''){const full=title?title+' · '+cfg.title:cfg.title+' · '+cfg.subtitle;return `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${e(full)}</title><meta name="description" content="${e(cfg.description)}"><meta name="site-base" content="${base}"><meta name="github-repository" content="${e(cfg.githubRepository)}">${origin?`<link rel="canonical" href="${origin}${url(route)}">`:''}<link rel="icon" href="${url('favicon.svg')}"><link rel="stylesheet" href="${url('style.css')}"><link rel="stylesheet" href="${url('highlight.css')}"><link rel="stylesheet" href="${url('katex/katex.min.css')}">${route==='write/'?`<script defer src="${url('writer.js')}"></script>`:route==='drafts/'?`<script defer src="${url('drafts.js')}"></script>`:''}<script src="${url('theme.js')}"></script><script defer src="${url('app.js')}"></script></head><body class="${['','notes/','topics/'].includes(route)?'portal-page':'reading-page'}"><a class="skip" href="#main">跳到正文</a><header><a class="brand" href="${base}">${e(cfg.title)}<span>学习手记</span></a><nav aria-label="主导航">${navItems.map(([r,label])=>`<a href="${url(r)}" ${route===r||r==='notes/'&&['archive/','tags/'].includes(route)||r==='topics/'&&(route==='series/'||route.startsWith('categories/'))?'aria-current="page"':''}>${label}</a>`).join('')}</nav><a class="write-link" href="${url('write/')}?new=1" ${route==='write/'?'aria-current="page"':''}>写一篇</a></header><main id="main"><div class="main-column">${body}</div></main><footer><span>© ${e(cfg.author)} · ${e(cfg.title)}</span><div class="footer-links"><button id="theme-toggle" aria-label="切换深浅主题">外观</button><a href="${url('publish/')}">发布指南</a><a href="${github}" target="_blank" rel="noopener">GitHub</a></div></footer><button id="back-top" aria-label="返回顶部" hidden>↑</button><div id="toast" role="status" hidden></div></body></html>`;}
function write(file,html){fs.mkdirSync(path.dirname(out+'/'+file),{recursive:true});fs.writeFileSync(out+'/'+file,html);}
const intro=`<section class="home-hero"><div><p class="author-note">${e(cfg.author)} 的个人博客</p><h1>学习手记</h1><p>记下学到的东西，还有一些自己的想法。</p><div class="hero-links"><a class="button primary" href="${url('notes/')}">翻翻笔记</a><a href="${url('write/')}?new=1">写下今天的收获 →</a></div></div><aside class="home-overview"><span>这本手记里</span><dl><div><dt>笔记</dt><dd>${posts.length}<small>篇</small></dd></div><div><dt>学习分类</dt><dd>${categories.length}<small>个</small></dd></div><div><dt>系列</dt><dd>${seriesNames.length}<small>组</small></dd></div></dl><a href="${url('about/')}">认识一下这里 →</a></aside></section>`;
write('index.html',layout('',intro+`<div class="home-columns"><section><div class="section-heading"><h2>最近写下</h2><a href="${url('notes/')}">全部笔记 →</a></div>${cards(posts.slice(0,3))||'<p class="muted">第一篇笔记还在路上。</p>'}</section><aside class="home-shortcuts"><h2>从这里开始</h2><a href="${url('topics/')}"><b>学习专题</b><span>沿着一个方向，读一组笔记</span></a><a href="${url('drafts/')}"><b>我的草稿</b><span>接着上次没写完的想法</span></a><a href="${url('music/')}"><b>听点音乐</b><span>选择歌单，或播放本地歌曲</span></a><a href="${url('archive/')}"><b>时间归档</b><span>回头看看以前的记录</span></a></aside></div><section class="home-topics"><div class="section-heading"><h2>按主题逛逛</h2><a href="${url('topics/')}">所有专题 →</a></div><div class="topic-grid">${categories.slice(0,4).map(c=>`<a class="topic-card" href="${url(categoryRoute(c))}"><small>${posts.filter(p=>p.category===c).length} 篇笔记</small><h3>${e(c)}</h3><span>打开这个分类 →</span></a>`).join('')||'<p class="muted">为文章填写分类后，会在这里形成主题。</p>'}</div></section>`));
write('notes/index.html',layout('全部笔记',`<section class="page-intro"><span class="page-kicker">笔记库</span><h1>全部笔记</h1><p>找一个知识点，或者随便翻一篇。</p></section>${subnav('notes/')}<div class="list-heading"><span id="result-count">${posts.length} 篇笔记</span><label class="search"><input id="search" type="search" placeholder="搜索标题或正文" aria-label="搜索笔记"></label></div><div class="filters"><button class="selected" data-filter="">全部分类</button>${categories.map(c=>`<button data-filter="${e(c)}">${e(c)}</button>`).join('')}</div><div id="post-list">${cards(posts)}</div><div id="empty" ${posts.length?'hidden':''}><h3>还没有笔记</h3><p>从今天学到的一件事开始。</p><a class="button primary" href="${url('write/')}?new=1">写一篇</a></div>`,'notes/'));
write('topics/index.html',layout('学习专题',`<section class="page-intro"><span class="page-kicker">沿着一个方向</span><h1>学习专题</h1><p>按分类找到相关笔记，按系列接着读下去。</p></section><div class="section-heading"><h2>笔记分类</h2><a href="${url('tags/')}">查看标签 →</a></div><div class="topic-grid">${categories.map(c=>{const list=posts.filter(p=>p.category===c);return `<section class="topic-card"><small>${list.length} 篇笔记</small><h2><a href="${url(categoryRoute(c))}">${e(c)}</a></h2><ul>${list.slice(0,2).map(p=>`<li><a href="${postUrl(p)}">${e(p.title)}</a></li>`).join('')}</ul><a class="topic-more" href="${url(categoryRoute(c))}">进入分类 →</a></section>`;}).join('')||'<p class="muted">发布第一篇文章后，分类会出现在这里。</p>'}</div><section class="series-area"><div class="section-heading"><h2>按系列阅读</h2><a href="${url('series/')}">系列目录 →</a></div>${seriesNames.length?seriesNames.map(name=>`<section class="series-box"><h3>${e(name)}</h3>${seriesList(name)}</section>`).join(''):`<div class="quiet-empty"><p>还没有连载系列。</p><p>写作时填写相同的系列名称，发布后就会自动收在这里。</p><a href="${url('write/')}?new=1">开始写一组笔记 →</a></div>`}</section>`,'topics/'));
for(const category of categories){const list=posts.filter(p=>p.category===category),route=categoryRoute(category);write(route+'index.html',layout(category,`<a class="back" href="${url('topics/')}">← 返回学习专题</a><section class="page-intro"><span class="page-kicker">笔记分类</span><h1>${e(category)}</h1><p>${list.length} 篇相关笔记，按最新时间排列。</p></section>${cards(list)}`,route));}
write('drafts/index.html',layout('我的草稿',`<section class="page-intro"><span class="page-kicker">留给自己的写作空间</span><h1>我的草稿</h1><p>想法可以先放着，下次再接着写。</p></section><div class="draft-page-heading"><p id="drafts-status" role="status">正在读取草稿…</p><a class="button primary" href="${url('write/')}?new=1">新建笔记</a></div><div id="drafts-list"></div><section id="drafts-empty" class="quiet-empty" hidden><h2>这里还没有草稿</h2><p>到写作页写下几句话，网站会自动保存。</p></section><p class="local-note">草稿和图片只保存在当前浏览器，不会公开，也不会自动同步到其他设备。重要内容请在写作页下载备份。</p>`,'drafts/'));
write('music/index.html',layout('音乐',`<section class="page-intro"><span class="page-kicker">给学习留一点背景声</span><h1>听点音乐</h1><p>选择一首歌，再慢慢读、慢慢写。</p></section>${music()}<p class="local-note">默认不会自动播放。本地歌曲仅在此页面播放；切换到其他页面时音乐会停止。可以把音乐页留在另一个标签页。</p><a class="text-button" href="${url('notes/')}" target="_blank" rel="noopener">在新标签页打开笔记 →</a>`,'music/'));
write('publish/index.html',layout('发布指南',`<section class="page-intro"><h1>发布一篇笔记</h1><p>写作与公开发布，是两个简单的步骤。</p></section><ol class="publish-steps"><li><h2>先写，再下载</h2><p>在<a href="${url('write/')}">写作页</a>填写标题和正文，点击「下载笔记」。没有图片会下载 Markdown，有图片会自动下载 ZIP。</p></li><li><h2>上传到 GitHub</h2><p>将 .md 文件上传到 <a href="${github}/upload/main/content/posts" target="_blank" rel="noopener">content/posts</a>。如果下载的是 ZIP，先解压，再把图片上传到 <a href="${github}/upload/main/public/images" target="_blank" rel="noopener">public/images</a>。</p></li><li><h2>提交，等网站更新</h2><p>在 GitHub 提交更改，自动部署完成后，文章会出现在<a href="${url('notes/')}">笔记页</a>。</p></li></ol><p class="local-note">草稿不会因下载而公开。只有仓库所有者或有写入权限的人能发布和编辑文章。</p>`,'publish/'));
for(let i=0;i<posts.length;i++){const p=posts[i],r=renderMarkdown(p.body,base),wordcount=p.body.replace(/\s/g,'').length;
write(`posts/${p.slug}/index.html`,layout(p.title,`<a class="back" href="${url('notes/')}">返回笔记</a><article class="reading"><div class="meta"><span class="badge">${e(p.category)}</span><time>${format(p.date)}</time><span>${wordcount} 字</span></div><h1>${e(p.title)}</h1><p class="byline">${e(cfg.author)}</p><details class="article-directory"><summary>文章目录</summary>${r.toc.map(h=>`<a class="toc-item depth-${h.depth}" href="#${h.id}">${e(h.title)}</a>`).join('')}</details><div class="prose">${r.html}</div>${p.series?`<section class="series-box"><h2>${e(p.series)}</h2><p class="muted">${p.seriesOrder?`当前：第 ${p.seriesOrder} 篇 · `:''}同系列学习笔记</p>${seriesList(p.series)}</section>`:''}<div class="tag-row">${p.tags.map(t=>`<a href="${url('tags/')}#${encodeURIComponent(t)}"># ${e(t)}</a>`).join('')}</div><div class="article-bottom"><button class="text-button" id="share-mobile">分享这篇</button><a href="${github}/edit/main/content/posts/${encodeURIComponent(p.file)}" target="_blank" rel="noopener">编辑文章</a></div><div class="adjacent">${posts[i+1]?`<a href="${postUrl(posts[i+1])}"><small>上一篇</small>${e(posts[i+1].title)}</a>`:'<span></span>'}${posts[i-1]?`<a href="${postUrl(posts[i-1])}"><small>下一篇</small>${e(posts[i-1].title)}</a>`:''}</div></article>`,`posts/${p.slug}/`));fs.mkdirSync(out+'/markdown',{recursive:true});fs.copyFileSync('content/posts/'+p.file,out+'/markdown/'+p.file);}
const groups=Object.groupBy(posts,p=>p.date.slice(0,7));write('archive/index.html',layout('文章归档',`<section class="page-intro"><h1>时间归档</h1><p>${posts.length} 篇笔记 · <a href="${url('tags/')}">按标签找</a> · <a href="${url('series/')}">查看系列</a></p></section>${subnav('archive/')}${Object.entries(groups).map(([month,list])=>`<section class="archive"><h2>${month.replace('-',' 年 ')} 月 <small>${list.length} 篇</small></h2>${list.map(p=>`<a href="${postUrl(p)}"><time>${p.date.slice(5).replace('-',' / ')}</time><b>${e(p.title)}</b><span>${e(p.category)}</span></a>`).join('')}</section>`).join('')||'<p class="muted">第一篇笔记保存后，会出现在这里。</p>'}`,'archive/'));
write('tags/index.html',layout('标签',`<section class="page-intro"><h1>标签</h1><p>找到同一个话题下的笔记。</p></section>${subnav('tags/')}<div class="tag-cloud">${tags.map(t=>`<a href="#${encodeURIComponent(t)}"># ${e(t)} <small>${posts.filter(p=>p.tags.includes(t)).length}</small></a>`).join('')}</div>${tags.map(t=>`<section class="tag-group" id="${e(t)}"><h2># ${e(t)}</h2>${cards(posts.filter(p=>p.tags.includes(t)))}</section>`).join('')||'<p class="muted">给笔记添加标签，在这里找到它们。</p>'}`,'tags/'));
write('about/index.html',layout('关于',`<section class="about-profile"><span class="profile-initial">${e(cfg.author.slice(0,1).toUpperCase())}</span><div><span class="page-kicker">写这本手记的人</span><h1>${e(cfg.author)}</h1><p>学习、实践，偶尔回头看看。</p></div></section><div class="prose"><p>${e(cfg.about)}</p><h2>我想留下什么</h2><p>值得反复读的笔记、实践中的发现，以及那些还没有想明白的问题。写下来，是为了更好地理解，也是为了以后还能找回来。</p><h2>慢慢来，也是一种进步</h2><p>这里的内容会随学习不断更新。欢迎阅读，也欢迎带着自己的问题继续探索。</p></div>`,'about/'));
write('series/index.html',layout('系列笔记',`<section class="page-intro"><h1>系列笔记</h1><p>把相关笔记放在一起，沿着自己的节奏深入学习。</p></section>${seriesNames.map(name=>`<section class="series-box"><h2>${e(name)}</h2><p class="muted">${orderedSeries(posts,name).length} 篇笔记</p>${seriesList(name)}</section>`).join('')||`<div class="series-box"><h2>你的第一个系列，从下一篇开始。</h2><p>写笔记时填写相同的「系列名称」和每篇的序号，发布后就会自动形成目录。</p><a class="button primary" href="${url('write/')}">写一篇系列笔记</a></div>`}`,'series/'));
write('write/index.html',layout('写笔记',`<section class="page-intro writer-intro"><h1>写一篇笔记</h1><p>先写下来，之后再慢慢补充。</p></section><section class="writer"><fieldset data-writer-control disabled><label class="title-label"><span class="sr-only">文章标题</span><input id="draft-title" placeholder="标题" maxlength="200" autocomplete="off"></label><div class="editor-tools"><button type="button" id="insert-image">插入图片</button><button type="button" id="toggle-preview" aria-pressed="false">预览</button><input id="image-file" type="file" accept="image/png,image/jpeg,image/webp,image/gif" multiple hidden></div><div class="editor-workspace" data-view="edit"><label class="edit-pane"><span class="sr-only">正文</span><textarea id="draft-body" rows="16" placeholder="今天学到了什么？从这里开始写。" aria-describedby="markdown-hint"></textarea></label><section class="preview-pane" aria-label="文章预览"><h2 id="preview-title"></h2><div id="draft-preview" class="prose"></div></section></div><div class="editor-bottom"><p id="save-status" role="status" aria-live="polite">正在恢复草稿…</p><span id="word-count">0 字</span><button type="button" id="download-draft" class="button primary">下载笔记</button></div><details class="writer-settings"><summary>文章设置</summary><div class="settings-content"><div class="writer-fields"><label>分类<input id="draft-category"></label><label>日期<input id="draft-date" type="date"></label></div><label>标签<input id="draft-tags" placeholder="用逗号分隔"></label><label>网址名<input id="draft-slug" placeholder="自动生成，可修改为小写英文"></label><div class="writer-fields"><label>系列名称<input id="draft-series" placeholder="可不填"></label><label>系列序号<input id="draft-seriesOrder" type="number" min="1" step="1" placeholder="可不填"></label></div><div class="image-details"><h3>图片附件</h3><div id="image-assets"></div></div><p class="muted" id="markdown-hint">支持 Markdown：## 标题、**粗体**、代码块和数学公式。直接写普通文字也可以。</p><p class="muted">草稿保存在当前浏览器。清除浏览器数据会删除草稿，重要内容请下载备份。</p></div></details></fieldset><div class="writer-page-links"><a href="${url('drafts/')}">查看所有草稿 →</a><a href="${url('publish/')}">如何发布笔记 →</a></div></section>`,'write/'));
write('404.html',layout('没有找到页面',`<section class="page-intro"><h1>这一页，还没有写下。</h1><p>文章可能已移动，你可以回到首页寻找。</p><a class="button primary" href="${base}">返回笔记</a></section>`));
fs.writeFileSync(out+'/music.json',JSON.stringify(cfg.music));fs.writeFileSync(out+'/search.json',JSON.stringify(posts.map(p=>({title:p.title,category:p.category,tags:p.tags,url:postUrl(p)}))));fs.writeFileSync(out+'/.nojekyll','');
if(origin){const urls=['','notes/','topics/','drafts/','music/','write/','publish/',...categories.map(categoryRoute),'archive/','tags/','series/','about/',...posts.map(p=>`posts/${p.slug}/`)];fs.writeFileSync(out+'/sitemap.xml',`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${urls.map(p=>`<url><loc>${e(origin+url(p))}</loc></url>`).join('')}</urlset>`);fs.writeFileSync(out+'/feed.xml',`<?xml version="1.0" encoding="UTF-8"?><rss version="2.0"><channel><title>${e(cfg.title)}</title><link>${e(origin+base)}</link><description>${e(cfg.description)}</description>${posts.map(p=>`<item><title>${e(p.title)}</title><link>${e(origin+postUrl(p))}</link><guid>${e(origin+postUrl(p))}</guid><pubDate>${new Date(p.date+'T12:00:00Z').toUTCString()}</pubDate><description>${e(p.summary)}</description></item>`).join('')}</channel></rss>`);}
console.log(`Built ${posts.length} posts at ${base}`);
